### ISSUE TITLE
Would you mind structuring your amps as a war overlay instead of in "standard" amp format?

### ISSUE THREAD

**Issue by binduwavell** [share-extras/js-console#19]
An AMP is essentially a WAR overlay for alfresco.war or share.war that includes a little extra metadata. Unfortunately by default AMPs have a structure that doesn't overlay cleanly, instead MMT does some moving of folders around. Fortunately it is possible to undo this strangeness by adding a file-mapping.properties file to your amp and organizing the folders in the AMP so they can be cleanly overlayed. The advantage to this is you are not stuck using MMT or the alfresco-maven-plugin wrapper of the same to overlay your amps, you can apply them simply by expanding the AMP over the exploded WAR... This is particularly useful in development where we want to use IDE support for web applications and overlaying to have performant development.

I have spoken with @mindthegab (Gab Columbro) and he plans to update the alfresco archetypes in this way... I was wondering if you would be up for doing this for your great alfresco extra?

If you are, here is a file-mapping.properties file that undoes the strange structure of an AMP, you do have to re-organize the stuff going into the amp so it is a clean overlay...

include.default=false
# The default AMP => WAR file mappings pulled from 4.1.3
#/config=/WEB-INF/classes
#/lib=/WEB-INF/lib
#/licenses=/WEB-INF/licenses
#/web/jsp=/jsp
#/web/css=/css
#/web/images=/images
#/web/scripts=/scripts
#/web/php=/php

#undo the defaults so we have a clean overlay
/css=/css
/images=/images
/jsp=/jsp
/scripts=/scripts
/WEB-INF/lib=/WEB-INF/lib
/WEB-INF/licenses=/WEB-INF/licenses

**Comment by jgoldhammer** [comment]
@AFaust , it is possible to have this for the new alfresco sdk? I think, it would be cool to have also jars available for faster deployment...

**Comment by jgoldhammer** [comment]
Provided by Tahir Malik
https://github.com/share-extras/js-console/pull/61

**Comment by mindthegab** [comment]
The new SDK (3.0.0 targeting Alfresco 5.1+) will have supported JAR modules, so hopefully all this non sense of AMPs and WAR overlays at Dev time, will finally go.

The ultimate objective is an immutable war, which nobody needs to change (either our or 3rd party modules).
