### ISSUE TITLE
JavaScript console fails to load on Internet Explorer 8

### ISSUE THREAD

**Issue by AFaust** [share-extras/js-console#24]
I do not know if anyone considers support of IE 8 as relevant, but due to the recent changes including tern.js and infer.js, the JavaScript console fails to load on Internet Explorer 8.

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Thu, 13 Feb 2014 11:44:45 UTC

Message: Expected ':'
Line: 7586
Char: 17
Code: 0
URI: http://alf-demo.prodyna.com/share/res/fme/components/jsconsole/jshint/jshint_fme.js

Message: Object doesn't support this property or method
Line: 12
Char: 3
Code: 0
URI: http://alf-demo.prodyna.com/share/res/fme/components/jsconsole/ternjs/tern/lib/tern_59e92da7d6f881a530f8791fe7462b.js

Message: Object doesn't support this property or method
Line: 44
Char: 5
Code: 0
URI: http://alf-demo.prodyna.com/share/res/fme/components/jsconsole/ternjs/tern/lib/infer_47a22cf73dbf3a345bae68ff0847b8.js

Message: Object doesn't support this property or method
Line: 220
Char: 16
Code: 0
URI: http://alf-demo.prodyna.com/share/res/components/console/consoletool_53c254baf73ecb0b64efeba641914.js

**Comment by jgoldhammer** [comment]
I think, we should not support IE8 anymore. So can I close the ticket?

**Comment by AFaust** [comment]
Resolution type: "Waited it out"
I think IE8 is not as relevant as when I opened the ticket (back then I actually did still have Alfresco customers on IE 8). At this point I'd say that it would not be worth the effort to fix it. Let's just hope that future changes / polyfills are more considerate to the web clients the majority of us dislike...
