### ISSUE TITLE
Logger.log() show nothing on Output Console

### ISSUE THREAD

**Issue by douglascrp** [share-extras/js-console#31]
I's been a while since Output Console doesn't work.
I'm using the latest version, built from source, running on Alfresco Community 4.2.f.
I got no errors on logs.
When I try to print something using logger.log(), on only can see the output looking at catalina.out and alfresco.log, but nothing on Output Console inside Share.

Any idea on how to solve this?

**Comment by jgoldhammer** [comment]
@douglascrp Problem still exists?

Thanks,
Jens

**Comment by douglascrp** [comment]
Not that I cam remember.
Close it and we can reopen it if it happens again.

**Comment by ohjrr2009** [comment]
Hi, the problem is back.

A simple code like:
print("Test");

does not work, but when I put more four lines of "prints"
print("Test");

print("");
print("");
print("");
print("");

the output comes to life again
