### ISSUE TITLE
JsConsoleDump.java is in the wrong directory

### ISSUE THREAD

**Issue by xkahn** [share-extras/js-console#32]
It needs to be moved from javascript-console-repo/source/java/de/fme/jsconsole/JsConsoleDump.java -> javascript-console-repo/src/main/java/de/fme/jsconsole/JsConsoleDump.java 

Until this file is moved, mvn compile will report missing symbols.

**Comment by AFaust** [comment]
Duplicate of #30

**Comment by jgoldhammer** [comment]
Closed as duplicate...
