### ISSUE TITLE
Error compiling repo project

### ISSUE THREAD

**Issue by tavvolley** [share-extras/js-console#34]
hi I'm Rocco and I have new in this forum! I have download the project into my workspace and I have compile both the project (share and repo). 
When I compile the project **javascript-console-repo** it make this error:
giuseppe@giuseppe-desktop:~/workspaceGit/js-console/javascript-console-repo$ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaScript Console - Repository 0.6.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- alfresco-maven-plugin:1.0.2:set-version (default-set-version) @ javascript-console-repo ---
[INFO] Added timestamp to version - 0.6.0.1501231041
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javascript-console-repo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 26 resources to ../javascript-console-repo-0.6.0
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ javascript-console-repo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/giuseppe/workspaceGit/js-console/javascript-console-repo/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,22] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[249,21] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[280,17] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[42,22] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[133,40] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,65] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[430,28] cannot find symbol
  symbol:   class JsConsoleDump
  location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.622s
[INFO] Finished at: Fri Jan 23 10:41:15 CET 2015
[INFO] Final Memory: 38M/327M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project javascript-console-repo: Compilation failure: Compilation failure:
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,22] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[249,21] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[280,17] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[42,22] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[133,40] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,65] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /home/giuseppe/workspaceGit/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[430,28] cannot find symbol
[ERROR] symbol:   class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

So I have see the code and I see that the class JsConsoleDump is not in the correct classpath.
I have search the class and I have found it at:
/source/java/de/fme/jsconsole
To solve the problem I copy the class JsConsoleDump in the folder:
/src/main/java/de/fme/jsconsole

**Comment by tavvolley** [comment]
Sorry I don't have read the other post. I have resolve the error and the I have read the post

**Comment by jgoldhammer** [comment]
Closed because this works now.
