### ISSUE TITLE
Version for Alfresco 5.X 

### ISSUE THREAD

**Issue by GuillermoCastillo** [share-extras/js-console#35]
HI:

Is there version of js-console for Alfresco 5.x ? 

Thanks

**Comment by wabson** [comment]
Generally the add-ons on share-extras should be forwards-compatible with future versions of Alfresco. If you find a problem please feel free to open a bug about that.

**Comment by jgoldhammer** [comment]
It is not compiled for Alfresco 5, but I have it running on Alfresco 5 without any problems.

Should we update the Alfresco sdk to 2.0?
CC: @wabson @fmaul @AFaust 

Thanks,
Jens

**Comment by AFaust** [comment]
This question came up on the IRC lately as well. Compatibility with 5.0 is given - the addons.alfresco.com listing should be adapted to reflect this (and maybe the release notes of previous release could also be appended).
As long as the update to SDK 2.0 does not introduce unecessary compatibility issues, I'd say do it. "Unecessary" would be being forced to use JDK 7 to compile which automatically excludes Alfresco 4.0/4.1 from compatibiliity. This would only be ok when it's a conscious decision to drop support for those older Alfresco versions.

**Comment by jgoldhammer** [comment]
@fmaul Can you update addons.alfresco.com?

**Comment by jgoldhammer** [comment]
@fmaul push. Can you update addons.alfresco.com?

**Comment by mathiaslin** [comment]
js-console (built from trunk) does not show up in Alfresco 5 / Admin Tools, see: https://github.com/share-extras/js-console/issues/42

**Comment by AFaust** [comment]
I have heard this a couple of times in the past, but in all 5.x instances I've used so far from 5.0.d to 5.0.1, JavaScript console always shows up even with the old release 0.6.0

**Comment by mathiaslin** [comment]
@AFaust I assume in both Enterprise and Community, it works for you then? Ok, I will investigate it a bit further...

**Comment by AFaust** [comment]
@jgoldhammer We'll have to revisit the update to latest Alfresco SDK since this currently prevents build of JS-Console to be compatible with Alfresco 4.2.x (see #55). I'll have a look at this later today.
