### ISSUE TITLE
repo amp not building with recent merge of dump functionality

### ISSUE THREAD

**Issue by binduwavell** [share-extras/js-console#36]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/bwavell/projects/js-console/javascript-console-repo/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,22] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[249,21] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[280,17] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[42,22] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[133,40] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,65] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[430,28] cannot find symbol
symbol  : class JsConsoleDump
location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[INFO] 7 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:36 min
[INFO] Finished at: 2015-02-16T14:30:08-07:00
[INFO] Final Memory: 37M/265M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project javascript-console-repo: Compilation failure: Compilation failure:
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,22] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[249,21] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[280,17] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[42,22] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleResult.java:[133,40] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleResult
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[71,65] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] /Users/bwavell/projects/js-console/javascript-console-repo/src/main/java/de/fme/jsconsole/JavascriptConsoleScriptObject.java:[430,28] cannot find symbol
[ERROR] symbol  : class JsConsoleDump
[ERROR] location: class de.fme.jsconsole.JavascriptConsoleScriptObject
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by docterwatson** [comment]
Having the same issue, missing JsConsoleDump class. Any word on this? Thanks much!

**Comment by MrBuddyCasino** [comment]
Same here.

**Comment by jgoldhammer** [comment]
@binduwavell , @docterwatson and @MrBuddyCasino 
Please try again after the new merge. Should not happen any more.
I will close the ticket. Please reopen it if you found any issues...

Thanks,
Jens
