### ISSUE TITLE
Latest release Javascript Console does not show up in Alfresco Share 5.0.0

### ISSUE THREAD

**Issue by nicolas-raoul** [share-extras/js-console#42]
I downloaded [the latest release](https://github.com/share-extras/js-console/releases/download/v0.6.0-rc1/javascript-console-share-0.6.0.amp) and installed it in my stopped Alfresco 5.0.0 like this:

```
java -jar bin/alfresco-mmt.jar install ~/Downloads/javascript-console-share-0.6.0.amp tomcat/webapps/share.war
```

After restarting Alfresco, the Javascript Console unfortunately does not show up:

![no-javascript-console](https://cloud.githubusercontent.com/assets/99590/7856929/ad1a03be-0567-11e5-82b4-ea8abe09a7f0.png)

What am I doing wrong?  
 [The latest release](https://github.com/share-extras/js-console/releases) is actually quite old (2013), maybe this bug could be fixed by doing a new release?
Thanks a lot!

**Comment by jgoldhammer** [comment]
Please build from trunk. 
Even with that I run into a blank issue in admin console.

**Comment by jgoldhammer** [comment]
Does that work for you, @nicolas-raoul ?

Thanks,
Jens

**Comment by nicolas-raoul** [comment]
@jgoldhammer: I was quite in a hurry so I actually used another ECM product.

In a perfect world releases would be up-to-date (as the manager of several open source project I know this is not always easy).

**Comment by mathiaslin** [comment]
@jgoldhammer: Same issue here with Alfresco 5.0.d (Community Edition). I built the latest js-console from the trunk. I deployed each jar to the alfresco/share's WEB-INF/lib respectively - just the same way I did for Alfresco 4.
But as @nicolas-raoul mentioned, it does not appear in the Admin Tools menu.

(It should be fine to just deploy the built jar files, no need to use alfresco-mmt.jar I assume? At least it worked fine with older Alfresco versions this way).

**Comment by douglascrp** [comment]
I'm using the 1.0 release against a 5.0.d server, and everything is working ok.
And I'm using amps to install it.

**Comment by nicolas-raoul** [comment]
@douglascrp: Interesting! What command line did you use to install it? Exact same command line as the one at the second line of the original post?

**Comment by mathiaslin** [comment]
@nicolas-raoul It now works for me in 5.0.d after I used the amp installation method. Just deploying the jars did not work; (if I remember correctly though, it used to work just fine in 4.x)

`C:\Alfresco\bin>java -jar alfresco-mmt.jar install C:\Users\mlin\Projects\js-console\javascript-console-repo\target\javascript-console-repo.amp C:\Alfresco\tomcat\webapps\alfresco.war`

`C:\Alfresco\bin>java -jar alfresco-mmt.jar install C:\Users\mlin\Projects\js-console\javascript-console-share\target\javascript-console-share.amp C:\Alfresco\tomcat\webapps\share.war`

**Comment by douglascrp** [comment]
I use the apply_amps script, which uses the alfresco-mmt.jar file

Em dom, 26 de jul de 2015 às 23:52, Nicolas Raoul <notifications@github.com>
escreveu:

**Comment by mathiaslin** [comment]
@nicolas-raoul As a side note: you should also make sure that you don't have any other third-party modules installed that eventually replace the entire share-custom-config.xml by accident, which might then make the share-custom-config.xml configuration within the js-console useless.

**Comment by jgoldhammer** [comment]
So can I close the ticket now or should we work on deploying the js-console as jar?

**Comment by LukaszRacon** [comment]
@nicolas-raoul I was able to deploy it as jars but I had to repackage/convert structure of amps to jars.

**Comment by shazada** [comment]
I once had a new assembly xmls from Axel and added a new profile as installable jars. I'm using that. It would be great to include those again. I don't really understand why 'not' to include them...

I can supply them. How would you like them?

**Comment by shazada** [comment]
I've added the following pull request, so accept it so we don't need to do this manually.

**Comment by jgoldhammer** [comment]
I will close the ticket for now. If there is any question left, please create a new ticket or reopen it here...
Thanks,
Jens
