### ISSUE TITLE
How to build js-console for alfresco 4.2?

### ISSUE THREAD

**Issue by johnkharvey** [share-extras/js-console#47]
Hello all,

I've got the current code, and am looking at commit 98dd1545cb09cca3cd218c6830ba41f117c14e59.

If I remember right:
 - Alfresco 5.0 is built with java 1.8
 - Alfresco 4.2 is built with java 1.7
 - Alfresco 4.0/4.1 are built with java 1.6

This seems to be somewhat validated in the release notes.
In README.md, I see this line about compiling for alfresco 4.0/4.1:
    mvn install -P Java6-crossCompile -Djdk6.executable=/path/to/javac

This is where the confusion starts.  The pom.xml's do not have a profile called Java6-crossCompile anywhere.  This makes me suspect that the documentation is out of date, and that this is no longer valid.

Furthermore, looking at the main pom-file for the js-console project, its parent can be found here:
https://repo1.maven.org/maven2/org/alfresco/maven/alfresco-sdk-parent/2.1.0/alfresco-sdk-parent-2.1.0.pom
When opened, it has this requirement:
   `<requireJavaVersion>`
   `<version>[1.8.0,)</version>`
   `<message>Alfresco 5.0.d and 5.0.1 runs on JDK8</message>`
   `</requireJavaVersion>`

So, this seems to further indicate that the code can only be compiled with java 1.8, i.e. alfresco 5.0 code.

With that being said, how do I generate an amp-file that is compatible with Alfresco 4.2?

**Comment by johnkharvey** [comment]
I think the answer is to use revision f390b2bd29013c522dc3d517dbcd327a60b6304f, which is the revision before the 5.0 SDK was added.

**Comment by jgoldhammer** [comment]
Yes, currently it is the only option because the sdk checks the java version as you have find out. Another option would be to have a branch of js-console for older alfresco versions. Any other option?

cc: @fmaul , @AFaust
