### ISSUE TITLE
JSConsole doesn't work on 4.2.f/4.2.4

### ISSUE THREAD

**Issue by aviriel** [share-extras/js-console#55]
Now it's impossible to use JSConsole on Alfresco 4.2.x. There are too types of errors:

1. Build JSConsole using Java 8, then install it to Alfresco 4.2 and see error "unsupported major.minor version 52.0". Alfresco cannot start.

2. Try to build JSConsole using Java 7, get error:
"[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Alfresco 5.0.d and 5.0.1 runs on JDK8"

**Comment by AFaust** [comment]
This is a result of update to latest SDK in context of #35 which forces Java 8. In #35 I cautioned against any upgrade that forced Java 7 - seems that we instead skipped that issue and went straight to Java 8.

**Comment by AFaust** [comment]
First check: It is not enough just to override the enforcer rules to allow Java 7 - the Alfresco SDK Maven plugins themselves have been compiled with Java 8 and won't work under Java 7.
