### ISSUE TITLE
search.findNode function not working

### ISSUE THREAD

**Issue by patriciay-appno** [share-extras/js-console#58]
Hi,

I have installed the javascript console in Alfresco 5.0.1.

I'm able to run the default demo script and get results, however, when I try to use search.findNode, I can't get any results

var node = search.findNode('workspace://SpacesStore/2b438ef2-9305-4924-b212-7b64eb796762');

print(node);
print(node.name);

Thanks

**Comment by jgoldhammer** [comment]
Hi,

can you please attach the repo logfiles here?
Is it possible to use utils.getNodeFromString (http://docs.alfresco.com/4.1/references/API-JS-Utility-getNodeFromString.html).

Thanks,
Jens

**Comment by patriciay-appno** [comment]
Hi Jens,

Thank you for your reply. That function doesn't work neither.

I notice that if I try to search with search.luceneSearch, some of the queries doesn't work, only the one that comes by default. 
However, if I try the same query in the node browser it works fine, even if I try for a specific node with the nodeRef.

**Comment by jgoldhammer** [comment]
Hi,

can you please attach the alfresco repository logfiles or stacktraces here?
Thanks,
Jens

**Comment by jgoldhammer** [comment]
No further reaction.
Please reopen the issue with more information.

Thanks,
Jens
