### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by fmaul** [share-extras/js-console#6]
Add a full screen button to use all the room on for large script/result windows:

``` javascript
  document.getElementById("page_x002e_ctool_x002e_admin-console_x0023_default-body").webkitRequestFullScreen();
  Dom.setStyle("page_x002e_ctool_x002e_admin-console_x0023_default-body", "width", "100%");
```

margins are needed, maybe fixed height and scrolling in result lists

**Comment by jgoldhammer** [comment]
Can you provide a pull request?

Thanks,
Jens
