### ISSUE TITLE
Brilliant! - is there a guide for beginners?

### ISSUE THREAD

**Issue by Tybion** [share-extras/js-console#60]
I have installed this on 5.0.d because I am writing a script for an 'Execute Script' Folder Rule and I am still struggling with learning Alfresco.  This seems to be an absolutely brilliant teaching tool - but do you have a guide for beginners?

**Comment by jgoldhammer** [comment]
Unfortunately not... Please check the official alfresco docs which are referenced in the menu docs on the js console admin page in share...
I hope, this helps.
Jens

**Comment by Tybion** [comment]
Thanks, Jens.

I have looked through the community doco and the Alfresco One doco, and I
can't find anything on Javascript Console - can you please give me link?

Regards,
David


On Fri, Oct 9, 2015 at 11:39 PM, Jens Goldhammer <notifications@github.com>
wrote:

> Unfortunately not... Please check the official alfresco docs which are
> referenced in the menu docs on the js console admin page in share...
> I hope, this helps.
> Jens
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/share-extras/js-console/issues/60#issuecomment-146855837>
> .
>



-- 
Blog: geofoss.net
