### ISSUE TITLE
ServerInfo fails looking up workflow definitions

### ISSUE THREAD

**Issue by trehak** [share-extras/js-console#64]
Running 5.0.d on Windows, when I click on Server Infos I get "Internal Server Error".

I suspect it has something to do with the fact that I deployed the Activiti wars (but I didn't deploy the Share integration) and Activiti is using the same database as Alfresco.

I attached the log files I got in the alfresco.log file.
[js-console-ServerInfo.txt](https://github.com/share-extras/js-console/files/36419/js-console-ServerInfo.txt)

**Comment by jgoldhammer** [comment]
Hi,

can you please check if your workflow is deployed correctly. It looks like that the definition is not valid bpmn, so I will close the ticket here because it is nothing related to js-console.

**Comment by trehak** [comment]
Fair enough, thanks, I'll look into the wf definitions. Cheers.
