### ISSUE TITLE
Get build errors using YUIcompressor bundled with new SDK 2.1.x 

### ISSUE THREAD

**Issue by trycoon** [share-extras/js-console#65]
As of Alfresco SDK 2.1.x or something, every Javascript is compressed by yuicompressor-maven-plugin and checked with jslint. If this project is built as a submodule to our ordinary All-in-one project the linter tests will also hit these Javascript-files, and fail the build:

[INFO] --- yuicompressor-maven-plugin:1.5.1:compress (compress-js) @ javascript-console-share ---
[INFO] beautify.js (86900b) -> beautify-min.js (31499b)[36%]
[INFO] dialog.js (4875b) -> dialog-min.js (2311b)[47%]
[INFO] placeholder.js (1722b) -> placeholder-min.js (991b)[57%]
[INFO] matchbrackets.js (5005b) -> matchbrackets-min.js (2380b)[47%]
[INFO] trailingspace.js (754b) -> trailingspace-min.js (373b)[49%]
[INFO] formatting.js (4413b) -> formatting-min.js (2375b)[53%]
[INFO] alfresco-templates.js (31578b) -> alfresco-templates-min.js (27263b)[86%]
[INFO] javascript-templates.js (2894b) -> javascript-templates-min.js (2722b)[94%]
[INFO] show-context-info.js (1562b) -> show-context-info-min.js (731b)[46%]
[INFO] show-hint.js (14153b) -> show-hint-min.js (7817b)[55%]
[INFO] templates-hint.js (9180b) -> templates-hint-min.js (3897b)[42%]
[INFO] text-hover.js (4827b) -> text-hover-min.js (2519b)[52%]
[INFO] token-hover.js (584b) -> token-hover-min.js (390b)[66%]
[INFO] hyperlink.js (3875b) -> hyperlink-min.js (2023b)[52%]
[INFO] javascript-lint.js (4203b) -> javascript-lint-min.js (1426b)[33%]
[INFO] json-lint.js (705b) -> json-lint-min.js (285b)[40%]
[INFO] lint.js (6866b) -> lint-min.js (3719b)[54%]
[INFO] remoting-lint.js (1337b) -> remoting-lint-min.js (648b)[48%]
[INFO] status-lint.js (2771b) -> status-lint-min.js (1292b)[46%]
[INFO] tern-jshint.js (955b) -> tern-jshint-min.js (469b)[49%]
[INFO] match-highlighter.js (4326b) -> match-highlighter-min.js (2079b)[48%]
[INFO] matchesonscrollbar.js (3339b) -> matchesonscrollbar-min.js (1875b)[56%]
[INFO] search.js (6785b) -> search-min.js (3400b)[50%]
[INFO] searchcursor.js (7471b) -> searchcursor-min.js (3433b)[45%]
[INFO] active-line.js (2193b) -> active-line-min.js (1030b)[46%]
[INFO] mark-selection.js (3532b) -> mark-selection-min.js (1661b)[47%]
[INFO] alfresco-batchprocessing-tern.js (897b) -> alfresco-batchprocessing-tern-min.js (718b)[80%]
[INFO] alfresco-json.js (325118b) -> alfresco-json-min.js (241037b)[74%]
[INFO] alfresco-webscripts-tern.js (14406b) -> alfresco-webscripts-tern-min.js (9562b)[66%]
[INFO] ecma5.json.js (51316b) -> ecma5.json-min.js (43478b)[84%]
[INFO] tern-extension.js (7009b) -> tern-extension-min.js (2827b)[40%]
[INFO] tern-hint.js (8720b) -> tern-hint-min.js (3453b)[39%]
[INFO] tern-hover.js (1490b) -> tern-hover-min.js (695b)[46%]
[INFO] tern-hyperlink.js (401b) -> tern-hyperlink-min.js (226b)[56%]
[INFO] tern.js (23395b) -> tern-min.js (11330b)[48%]
[INFO] worker.js (1207b) -> worker-min.js (764b)[63%]
[INFO] extra.js (2936b) -> extra-min.js (1642b)[55%]
[INFO] codemirror.js (343471b) -> codemirror-min.js (169388b)[49%]
[INFO] parsefreemarker.js (14820b) -> parsefreemarker-min.js (4301b)[29%]
[INFO] htmlmixed.js (4620b) -> htmlmixed-min.js (2409b)[52%]
[INFO] javascript.js (26082b) -> javascript-min.js (14104b)[54%]
[INFO] codemirror-ui-find.js (2175b) -> codemirror-ui-find-min.js (1498b)[68%]
[INFO] codemirror-ui.js (16558b) -> codemirror-ui-min.js (9117b)[55%]
[INFO] map.js (3115b) -> map-min.js (1684b)[54%]
[INFO] javascript-console.js (98421b) -> javascript-console-min.js (45209b)[45%]
[INFO] jquery.min.js (93868b) -> jquery.min-min.js (94420b)[100%]
[INFO] logtail.js (4465b) -> logtail-min.js (1635b)[36%]
[INFO] jsconsole-actions.js (779b) -> jsconsole-actions-min.js (507b)[65%]
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [385:14]: missing name after . operator
[ERROR] ...jshint_fme - Kopie.js:line 385:column 14:missing name after . operator
	assert.throws = function(block, /*optional*/error, /*optional*/message) {
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [386:11]: syntax error
[ERROR] ...jshint_fme - Kopie.js:line 386:column 11:syntax error
	  _throws.apply(this, [true].concat(pSlice.call(arguments)));
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [387:2]: missing ] after element list
[ERROR] ...jshint_fme - Kopie.js:line 387:column 2:missing ] after element list
	};
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [404:14]: missing ) in parenthetical
[ERROR] ...jshint_fme - Kopie.js:line 404:column 14:missing ) in parenthetical
	},{"util/":9}],5:[function(require,module,exports){
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [426:25]: missing ; before statement
[ERROR] ...jshint_fme - Kopie.js:line 426:column 25:missing ; before statement
	function EventEmitter() {
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [427:8]: syntax error
[ERROR] ...jshint_fme - Kopie.js:line 427:column 8:syntax error
	  this._events = this._events || {};
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [429:1]: syntax error
[ERROR] ...jshint_fme - Kopie.js:line 429:column 1:syntax error
	}
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [430:8]: syntax error
[ERROR] ...jshint_fme - Kopie.js:line 430:column 8:syntax error
	module.exports = EventEmitter;
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [707:1]: syntax error
[ERROR] ...jshint_fme - Kopie.js:line 707:column 1:syntax error
	},{}],6:[function(require,module,exports){
[ERROR] /Users/hosa/Documents/git/alfresco/alfresco_src/js-console/javascript-console-share/src/main/amp/web/fme/components/jsconsole/jshint/jshint_fme - Kopie.js [708:42]: missing ; before statement
[ERROR] ...jshint_fme - Kopie.js:line 708:column 42:missing ; before statement
	if (typeof Object.create === 'function') {

and more....

There seems to be no way of disabling these tests or exclude the js-console directory. If there is a way please get back to me! Otherwise js-console need to be cleaned up to pass general linter tests, most of the errors are simple missing semicolons.

Here are the settings in Alfresco SDK: https://github.com/Alfresco/alfresco-sdk/blob/f031c76a41962c0fa605813ae0d1f0bd828b9a2f/poms/alfresco-sdk-parent/pom.xml, search for "net.alchim31.maven".

**Comment by jgoldhammer** [comment]
It should work now. Please reopen the ticket if it does not work for you...
