### ISSUE TITLE
Make methods of class extending BaseScopableProcessorExtension available for autocomplete

### ISSUE THREAD

**Issue by lutzhorn** [share-extras/js-console#67]
What is the recommended way to make the methods of a class extending `BaseScopableProcessorExtension` available for autocompletion in the JS Console?

Writing a Surf extension (XML plus JS defining the methods) looks quite complicated.

**Comment by lutzhorn** [comment]
Ping.

Can you please provide some advice.

**Comment by AFaust** [comment]
The tern files for js-console are pre-generated and not really designed for customization. In my branch for Aikau-ification of the js-console I have actually implemented a web script (https://github.com/AFaust/js-console/blob/js-console-v2/javascript-console-repo/src/main/java/de/fme/jsconsole/AlfrescoScriptAPITernGet.java) to dynamically generate a tern document (without doc element at the moment). This web script would automatically detect and process any processor extensions as it inpsects a default web script model and uses reflection to traverse all dependencies / operations.

**Comment by jgoldhammer** [comment]
@lutzhorn you can also provide tern files for the old javascript console. 
You can find examples here:
https://github.com/share-extras/js-console/tree/master/javascript-console-share/src/main/amp/web/fme/components/jsconsole/codemirror/addon/tern/defs

You can write these files by hand
