### ISSUE TITLE
Alfresco 5.1 document root object

### ISSUE THREAD

**Issue by sorrentinov** [share-extras/js-console#68]
Hi
I'm trying to use your js-console in Alfresco 5.1.e version that is very good.
When I click on execute in on of test js scripts I receive:

041941020 ReferenceError: "document" is not defined

In attachment the screenshot
![Uploading Alfresco_Javascript_console_error.png…]()

I do something wrong? Alfresco 5.1.e is supported
Thanks in advance

**Comment by jgoldhammer** [comment]
Hi, can you please attach the screenshot or the test script plus stacktrace from the server?
Thx, Jens

**Comment by sorrentinov** [comment]
Hi, 
The test script is in your sample (I clicked on Load Script-->example test script.js.sample)
The stacktrace that appear in your console is:

`500 Internal Error Stacktrace-Details: org.springframework.extensions.webscripts.WebScriptException: 042329723 Wrapped Exception (with status template): 0423118836 Failed to execute script 'Javascript Console Script': 0423118835 ReferenceError: "document" is not defined. (Javascript Console Script#23) at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138) at de.fme.jsconsole.ExecuteWebscript.executeScriptContent(ExecuteWebscript.java:405) at de.fme.jsconsole.ExecuteWebscript.access$100(ExecuteWebscript.java:56) at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java:280) at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java:273) at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457) at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345) at de.fme.jsconsole.ExecuteWebscript.runWithTransactionIfNeeded(ExecuteWebscript.java:272) at de.fme.jsconsole.ExecuteWebscript.access$000(ExecuteWebscript.java:56) at de.fme.jsconsole.ExecuteWebscript$1.doWork(ExecuteWebscript.java:250) at de.fme.jsconsole.ExecuteWebscript$1.doWork(ExecuteWebscript.java:247) at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548) at de.fme.jsconsole.ExecuteWebscript.runScriptWithTransactionAndAuthentication(ExecuteWebscript.java:247) at de.fme.jsconsole.ExecuteWebscript.execute(ExecuteWebscript.java:121) at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:460) at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:649) at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:421) at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:301) at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378) at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209) at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132) at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466) at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Unknown Source) Caused by: org.alfresco.scripts.ScriptException: 0423118836 Failed to execute script 'Javascript Console Script': 0423118835 ReferenceError: "document" is not defined. (Javascript Console Script#23) at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:204) at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:212) at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:174) at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:102) at de.fme.jsconsole.ExecuteWebscript.executeScriptContent(ExecuteWebscript.java:348) ... 44 more Caused by: org.alfresco.error.AlfrescoRuntimeException: 0423118835 ReferenceError: "document" is not defined. (Javascript Console Script#23) at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:526) at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:200) ... 48 more Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "document" is not defined. (Javascript Console Script#23) at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687) at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665) at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3750) at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1728) at org.mozilla.javascript.gen.Javascript_Console_Script_23._c_script_0(Javascript Console Script:23) at org.mozilla.javascript.gen.Javascript_Console_Script_23.call(Javascript Console Script) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.mozilla.javascript.gen.Javascript_Console_Script_23.call(Javascript Console Script) at org.mozilla.javascript.gen.Javascript_Console_Script_23.exec(Javascript Console Script) at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:502) ... 49 more An error inside the HTTP server which prevented it from fulfilling the request. 0423118835 ReferenceError: "document" is not defined. (Javascript Console Script#23)`

Thx
Vincenzo

**Comment by sazasalamer** [comment]
Hi sorrentinov !
I've another problem!
I'd like to integrate the chat module on my alfresco 5.0d and i need your help.
I want to know what to do and how to do it!
I'm looking forward for a favorable reply.

**Comment by jgoldhammer** [comment]
The document root object has to be filled by you- this kind of script needs a selection of a document. So please try to use the standard script.
If this does not work, please create a new ticket.
