### ISSUE TITLE
version numbering not up to date

### ISSUE THREAD

**Issue by shazada** [share-extras/js-console#69]
The version number isn't really up to date with the development.
We're still on 0.6 which is the same as last year and If I'm not mistaken the final 4.2 release.
Internally we've upped the number to 0.6.3 (alfresco 5.1 compatible) and 0.6.2 (alfresco 5.0 compatible).

I'd suggest we up the nr every x commits or similar.

**Comment by jgoldhammer** [comment]
We will keep on eye on the versioning in the future.
Next version will be 1.0, compatible with Alfresco 5.1
