### ISSUE TITLE
future of aikau based js-console

### ISSUE THREAD

**Issue by jgoldhammer** [share-extras/js-console#73]
@AFaust Is it realistic that the aikau based js-console will be the same feature level like the current js-console? What do you think from your perspective? What is your plan?

**Comment by AFaust** [comment]
I am generally aiming for the same feature level but some features may be hard to keep or need to be addressed differently. I.e. the FreeMarker highlighting support is not compatible with the newer CodeMirror version and I haven't found an updated version of the plugin.

**Comment by jgoldhammer** [comment]
Seems you no longer work on it. Closing now.

**Comment by AFaust** [comment]
Has lower priority than other projects right now, but not abandoned / given up in general...
