### ISSUE TITLE
Opening the JS Console on a large Alfresco 4.2 instance, takes down Alfresco

### ISSUE THREAD

**Issue by tgeens** [share-extras/js-console#75]
The environment is an Alfresco EE 4.2 with about 10M documents.

Opening the JS Console triggers some very broad searches to count documents/folders/... This will run as an unbounded metadata-query on the db. Those db-queries ran for more than an hour before the DBA aborted the running queries in msyql. During that time, Alfresco was more or less unavailable.

Starting point: https://github.com/share-extras/js-console/blob/v0.6.0-rc1/javascript-console-repo/src/main/amp/config/alfresco/extension/templates/webscripts/de/fme/jsconsole/serverInfo.get.js

**Comment by tgeens** [comment]
@AFaust already mentioned this issue in https://github.com/share-extras/js-console/issues/33#issuecomment-124990017

**Comment by AFaust** [comment]
The 0.6.0 release published on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cjavascript-console) has a lot of enhancements over the 0.6.0-rc1. Unfortunately, no tag or release was created for that on GitHub. One improvement is that server info has been moved to a secondary tab of the UI and will not be loaded without active action by the admin (must be requested). This is part of the commit c1c95e801a059cbb940c385a862af2d417d98877

**Comment by AFaust** [comment]
The types of queries to determine number of documents etc. should be best dealt via SOLR and just use the "numberFound" result metadata instead of actually fetching all results. Unfortunately, unless [ALF-21824|https://issues.alfresco.com/jira/browse/ALF-21824] has been addressed there is no way to force EVENTUAL consistency for searches from Script API.

**Comment by jgoldhammer** [comment]
Closed for now. Please use the newer version.
There is nothing i can do at the moment (besides removing the code). If somebody is interested in removing it, please submit a pr.

Thanks
Jens
