### ISSUE TITLE
Compatibility with alfresco 5.2

### ISSUE THREAD

**Issue by josecanoixxus** [share-extras/js-console#77]
There is a problem if we use it with alfresco 5.2

Invocation of init method failed; nested exception is org.alfresco.service.cmr.dictionary.DictionaryException: 07160001 Could not import bootstrap model 'alfresco/module/de.fme.alfresco.JavascriptConsole-repo/model/fme-jsconsole-model.xml'

**Comment by douglascrp** [comment]
Hello.

I am using it with Alfresco 5.2 without that problem.

**Comment by jgoldhammer** [comment]
Any input @josecanoixxus ? Please reopen the ticket if you have more details for us. Thanks, Jens
