### ISSUE TITLE
js-console does not show up in the left-hand-side panel after building per README.md

### ISSUE THREAD

**Issue by nicolas-raoul** [share-extras/js-console#83]
I just built and installed js-console, as per README.md:

1. Stop Alfresco
2. mvn install
3. In Alfresco's bin folder: `java -jar alfresco-mmt.jar install ~/src/js-console/javascript-console-repo/target/javascript-console-repo-0.7-SNAPSHOT.amp ../tomcat/webapps/alfresco.war`
4. In Alfresco's bin folder: `java -jar alfresco-mmt.jar install ~/src/js-console/javascript-console-share/target/javascript-console-share-0.7-SNAPSHOT.amp ../tomcat/webapps/share.war`
5. Start Alfresco
6. Log in and open the Admin Tools
7. Expected: "Javascript Console" link in the left panel. Actually: No link.

![screenshot from 2018-01-17 13-26-34](https://user-images.githubusercontent.com/99590/35025679-321db86a-fb8a-11e7-913f-77adf40e1cd2.png)

Alfresco Alfresco Community 201707 v5.2.0 (re21f2be5-b22) schema 10057

**Comment by jgoldhammer** [comment]
Thanks for the information. 
Any information in the logfiles available?

**Comment by nicolas-raoul** [comment]
@jgoldhammer alfresco.log and share.log attached, it does not seem to contain anything related to js-console.
[alfresco.log](https://github.com/share-extras/js-console/files/1638200/alfresco.log)
[share.log](https://github.com/share-extras/js-console/files/1638204/share.log)
Are there other log files to look for?

**Comment by jgoldhammer** [comment]
Thanks.
The modules are not installed in repo and share correctly- the log output does not contain the modules for it. Please check the output of mmt.jar commands and check if the war files contains the modules.

**Comment by nicolas-raoul** [comment]
Indeed, using the installation method described at https://geofoss.net/2015/10/12/using-javascript-console-to-create-a-folder-rule-script-in-alfresco/ did the trick, thanks!
