### ISSUE TITLE
Install Javascript Console in Alfresco Community 7.1

### ISSUE THREAD

**Issue by marcogianini** [share-extras/js-console#99]
I used version 6.0 repo.amp and share.amp on a 7.1 Alfresco Community installation.

And it's generating the following message inside the JavaScript Console panel when I try to run any script. Using the test scripts we have in the repository.

500 Internal Error
Stacktrace-Details:

An error inside the HTTP server which prevented it from fulfilling the request.
org/apache/commons/lang/StringUtils

Does it have to recompile with SDK update?
Or has anyone successfully installed on 7.1 and what AMP was used?

Thanks

**Comment by sergefedorow** [comment]
Use 0.7 version of modules.

**Comment by marcogianini** [comment]
Thanks Serge.

I located version 0.7 and installed it successfully.

Thank you very much.
